displayName=Death Notifications Secure
author=gaailiunas
support=
description=Sends a message to a relay webserver when dying while hiding the webhook URL.
tags=death,webhook,secure
plugins=moe.cuteanimegirls.discorddeathnotifications.DeathNotificationsPlugin